batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - mesnardo/amgxwrapper:1.4-GPU-IntelMPI-ubuntu
  volumes:
    shared_data_volumes:
      glustervol:
        volume_driver: glusterfs_on_compute
        container_path: $AZ_BATCH_NODE_SHARED_DIR/gfs
        bind_options: rw
      azurefilevol:
        volume_driver: azurefile
        storage_account_settings: mystorageaccount
        azure_file_share_name: fileshare
        container_path: $AZ_BATCH_NODE_SHARED_DIR/azfile
        mount_options:
        - file_mode=0777
        - dir_mode=0777
        bind_options: rw
  files:
  - source:
      path: .
      exclude:
      - '*shipyard*'
      - '*output*'
    destination:
      shared_data_volume: glustervol
      relative_destination_path: poisson
      data_transfer:
        method: rsync+ssh
